name: CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: arfath-portfolio/package.json

      - name: Install dependencies
        working-directory: arfath-portfolio
        run: npm ci

      - name: Lint
        working-directory: arfath-portfolio
        run: npm run lint --if-present

      - name: Typecheck
        working-directory: arfath-portfolio
        run: npm run typecheck --if-present

      - name: Build
        working-directory: arfath-portfolio
        run: npm run build --if-present

